/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppShellRouteImport } from './routes/_appShell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppShellPatientsIndexRouteImport } from './routes/_appShell/patients/index'
import { Route as AppShellLaraIndexRouteImport } from './routes/_appShell/lara/index'
import { Route as AppShellHomeIndexRouteImport } from './routes/_appShell/home/index'
import { Route as AppShellAppointmentsIndexRouteImport } from './routes/_appShell/appointments/index'

const AppShellRoute = AppShellRouteImport.update({
  id: '/_appShell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellPatientsIndexRoute = AppShellPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellLaraIndexRoute = AppShellLaraIndexRouteImport.update({
  id: '/lara/',
  path: '/lara/',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellHomeIndexRoute = AppShellHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AppShellRoute,
} as any)
const AppShellAppointmentsIndexRoute =
  AppShellAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => AppShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppShellAppointmentsIndexRoute
  '/home': typeof AppShellHomeIndexRoute
  '/lara': typeof AppShellLaraIndexRoute
  '/patients': typeof AppShellPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppShellAppointmentsIndexRoute
  '/home': typeof AppShellHomeIndexRoute
  '/lara': typeof AppShellLaraIndexRoute
  '/patients': typeof AppShellPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_appShell': typeof AppShellRouteWithChildren
  '/_appShell/appointments/': typeof AppShellAppointmentsIndexRoute
  '/_appShell/home/': typeof AppShellHomeIndexRoute
  '/_appShell/lara/': typeof AppShellLaraIndexRoute
  '/_appShell/patients/': typeof AppShellPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/appointments' | '/home' | '/lara' | '/patients'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/appointments' | '/home' | '/lara' | '/patients'
  id:
    | '__root__'
    | '/'
    | '/_appShell'
    | '/_appShell/appointments/'
    | '/_appShell/home/'
    | '/_appShell/lara/'
    | '/_appShell/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppShellRoute: typeof AppShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_appShell': {
      id: '/_appShell'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appShell/patients/': {
      id: '/_appShell/patients/'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AppShellPatientsIndexRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_appShell/lara/': {
      id: '/_appShell/lara/'
      path: '/lara'
      fullPath: '/lara'
      preLoaderRoute: typeof AppShellLaraIndexRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_appShell/home/': {
      id: '/_appShell/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppShellHomeIndexRouteImport
      parentRoute: typeof AppShellRoute
    }
    '/_appShell/appointments/': {
      id: '/_appShell/appointments/'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppShellAppointmentsIndexRouteImport
      parentRoute: typeof AppShellRoute
    }
  }
}

interface AppShellRouteChildren {
  AppShellAppointmentsIndexRoute: typeof AppShellAppointmentsIndexRoute
  AppShellHomeIndexRoute: typeof AppShellHomeIndexRoute
  AppShellLaraIndexRoute: typeof AppShellLaraIndexRoute
  AppShellPatientsIndexRoute: typeof AppShellPatientsIndexRoute
}

const AppShellRouteChildren: AppShellRouteChildren = {
  AppShellAppointmentsIndexRoute: AppShellAppointmentsIndexRoute,
  AppShellHomeIndexRoute: AppShellHomeIndexRoute,
  AppShellLaraIndexRoute: AppShellLaraIndexRoute,
  AppShellPatientsIndexRoute: AppShellPatientsIndexRoute,
}

const AppShellRouteWithChildren = AppShellRoute._addFileChildren(
  AppShellRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppShellRoute: AppShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
